

class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTranformationArtifact:...
class ModeltrainerArtifact:...
class ModelEvalutionArtifact:...
class ModelPusherArtifact:...



